# Generated by Django 5.1.2 on 2024-10-12 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('last_oil', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='note_image/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='car_app.car')),
            ],
        ),
        migrations.CreateModel(
            name='Oil_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millage_oil', models.IntegerField(verbose_name='Пробег сейчас')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('name_oil', models.CharField(max_length=20, verbose_name='Название масла')),
                ('next_millage_oil', models.IntegerField(verbose_name='Следущая замена масла')),
                ('image', models.ImageField(upload_to='oil_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_part', models.TextField()),
                ('price_spare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена запчасти')),
                ('price_work', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена работы')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(upload_to='service_image/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='car_app.car')),
            ],
        ),
    ]
