# Generated by Django 5.1.2 on 2024-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_goodspare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oil_service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='oil_images/'),
        ),
    ]
