# Generated by Django 5.1.2 on 2024-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_alter_oil_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodspare',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='good-spare/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_image/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='service_image/'),
        ),
    ]
